name: Release Pipeline
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions: read-all

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: typo-scanner

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -o ${{ env.IMAGE_NAME }}

      - name: scan some
        run: ./${{ env.IMAGE_NAME }} npm -drsv express bluebird

